---
- name: update web, nfs and db servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is uninstalled
      yum:
        name: wireshark
        state: absent

- name: update DB server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is uninstalled
      apt:
        name: nginx
        state: absent