---
- name: update web, nfs and db servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is installed
      yum:
        name: wireshark
        state: latest

- name: update DB server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is installed
      apt:
        name: wireshark
        state: latest

    - name: Change file ownership, group and permission
      ansible.builtin.file:
      path: /home/ubuntu/new-folder
      state: directory
      mode: '0644'

      