---
- name: update web, nfs and db servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is installed
      yum:
        name: wireshark
        state: latest

- name: update DB server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is installed
      apt:
        name: wireshark
        state: latest

- name: Create a directory if it does not exist:
  ansible.builtin.file:
    path: /home/ubuntu/ans-file-folder
    state: directory
    mode: '0755'